
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Product, CartItem, User } from '../types';
import { storeService } from '../services/storeService';

interface CartContextType {
  cart: CartItem[];
  addToCart: (product: Product, quantity?: number, notes?: string) => void;
  removeFromCart: (productId: string) => void;
  updateQuantity: (productId: string, quantity: number) => void;
  updateNotes: (productId: string, notes: string) => void;
  clearCart: () => void;
  submitOrder: () => Promise<void>;
  totalItems: number;
  totalWeight: number;
  isCartOpen: boolean;
  setIsCartOpen: (isOpen: boolean) => void;
}

const CartContext = createContext<CartContextType | undefined>(undefined);

export const useCart = () => {
  const context = useContext(CartContext);
  if (!context) throw new Error('useCart must be used within a CartProvider');
  return context;
};

export const CartProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [isCartOpen, setIsCartOpen] = useState(false);

  // Persist cart to local storage
  useEffect(() => {
    const savedCart = localStorage.getItem('sanghavi_b2b_cart');
    if (savedCart) {
      try {
        setCart(JSON.parse(savedCart));
      } catch (e) {
        console.error("Failed to parse cart", e);
      }
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('sanghavi_b2b_cart', JSON.stringify(cart));
  }, [cart]);

  const addToCart = (product: Product, quantity = 1, notes = '') => {
    setCart(prev => {
      const existing = prev.find(item => item.product.id === product.id);
      if (existing) {
        return prev.map(item => 
          item.product.id === product.id 
            ? { ...item, quantity: item.quantity + quantity }
            : item
        );
      }
      return [...prev, { product, quantity, notes }];
    });
    // Optional: Auto open cart on first add or show toast
    if (navigator.vibrate) navigator.vibrate(20);
  };

  const removeFromCart = (productId: string) => {
    setCart(prev => prev.filter(item => item.product.id !== productId));
  };

  const updateQuantity = (productId: string, quantity: number) => {
    if (quantity < 1) {
        removeFromCart(productId);
        return;
    }
    setCart(prev => prev.map(item => item.product.id === productId ? { ...item, quantity } : item));
  };

  const updateNotes = (productId: string, notes: string) => {
    setCart(prev => prev.map(item => item.product.id === productId ? { ...item, notes } : item));
  };

  const clearCart = () => setCart([]);

  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
  const totalWeight = cart.reduce((sum, item) => sum + (item.product.weight * item.quantity), 0);

  const submitOrder = async () => {
    const user = storeService.getCurrentUser();
    const config = await storeService.getConfig();
    const adminPhone = config.whatsappNumber ? config.whatsappNumber.replace(/\D/g, '') : '';
    
    // 1. Format Message
    let message = `*B2B PURCHASE ORDER*\n`;
    message += `Client: ${user?.name || 'Guest'} (${user?.phone || 'No Phone'})\n`;
    message += `Date: ${new Date().toLocaleDateString()}\n`;
    message += `-----------------------------\n`;
    
    cart.forEach((item, idx) => {
        message += `${idx + 1}. *${item.product.title}* (#${item.product.id.slice(-6)})\n`;
        message += `   Qty: ${item.quantity} | Wt: ${item.product.weight}g\n`;
        if (item.notes) message += `   Note: ${item.notes}\n`;
        message += `\n`;
    });
    
    message += `-----------------------------\n`;
    message += `*Total Qty:* ${totalItems}\n`;
    message += `*Est. Total Weight:* ${totalWeight.toFixed(2)}g\n`;
    message += `\n[Auto-Generated by Sanghavi B2B App]`;

    // 2. Log to Analytics/DB
    await storeService.logEvent('b2b_order', undefined, user, undefined, undefined);

    // 3. Open WhatsApp
    const waUrl = `https://wa.me/${adminPhone}?text=${encodeURIComponent(message)}`;
    window.open(waUrl, '_blank');
    
    // 4. Clear Cart
    clearCart();
    setIsCartOpen(false);
  };

  return (
    <CartContext.Provider value={{ 
      cart, addToCart, removeFromCart, updateQuantity, updateNotes, clearCart, 
      submitOrder, totalItems, totalWeight, isCartOpen, setIsCartOpen 
    }}>
      {children}
    </CartContext.Provider>
  );
};
